export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#241a00",
        "inverse-surface": "#30312e",
        "on-tertiary-fixed-variant": "#574500",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#8ef6ce",
        outline: "#6e7a73",
        "surface-variant": "#e4e2dd",
        "surface-dim": "#dbdad5",
        "on-error-container": "#93000a",
        "on-surface-variant": "#3e4944",
        "on-tertiary-container": "#4f3e00",
        "tertiary-fixed": "#ffe088",
        surface: "#fbf9f4",
        primary: "#006b50",
        "primary-container": "#008766",
        background: "#fbf9f4",
        "on-primary-fixed": "#002116",
        "surface-tint": "#006c51",
        "on-primary-container": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#71dab3",
        "on-secondary-container": "#3c5781",
        "surface-bright": "#fbf9f4",
        tertiary: "#735c00",
        "secondary-container": "#b2cdfe",
        "surface-container": "#f0eee9",
        "inverse-on-surface": "#f2f1ec",
        "on-surface": "#1b1c19",
        "secondary-fixed-dim": "#adc7f8",
        "on-primary": "#ffffff",
        "surface-container-high": "#eae8e3",
        "on-secondary-fixed": "#001b3d",
        "inverse-primary": "#71dab3",
        "surface-container-highest": "#e4e2dd",
        "secondary-fixed": "#d6e3ff",
        secondary: "#455f8a",
        "tertiary-container": "#cca830",
        "on-secondary-fixed-variant": "#2c4771",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#e9c349",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#00513c",
        "surface-container-low": "#f5f3ee",
        "outline-variant": "#bdcac2",
        "error-container": "#ffdad6",
        "on-background": "#1b1c19",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "20px",
        gutter: "24px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        unit: "8px",
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans"],
        "label-caps": ["Plus Jakarta Sans"],
        "headline-sm": ["Libre Caslon Text"],
        "display-lg": ["Libre Caslon Text"],
        "headline-md": ["Libre Caslon Text"],
        "body-lg": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Libre Caslon Text"],
      },
    },
  },
  plugins: [],
}
